<a href="https://colab.research.google.com/github/takasshii/deeplearning_udemy/blob/main/python%E3%81%AE%E5%9F%BA%E7%A4%8E.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##タプル
挿入や削除といった操作ができない以外はリストと同じである。
()で囲むことでタプルになる。

In [ ]:
a = (1, 2, 3, 4, 5)     # タプルの作成
b = (3,) #一つの場合は,を最後つける必要がある

b = a[2]                # 3番目の要素を取得
print(b)

##セット
重複した値を持つことができない

In [ ]:
a = [1, 1, 2, 3, 4, 4, 5, 5, 5]  # リスト
print(a)

b = set(a)  # セットに変換
print(b)

b.add(6)  # 値を追加
print(b)

b.remove(3)  # 値を削除
print(b)

##内包表記
```
新たなリスト = [ 要素への処理 for 要素 in リスト]  
```

In [ ]:
a = [1, 2, 3, 4, 5, 6]
b = [c*3+1 for c in a]    # aの要素を3倍して1を足し新たなリストを作る
print(b)

##行列の計算

In [ ]:
# dot → 通常の積
import numpy as np

a = np.array([[0,1,2],
             [1,2,3]])
b = np.array([[2,1],[2,1],[2,1]])

print(np.dot(a,b))

[[ 6  3]
 [12  6]]


In [ ]:
# * 要素ごとの積
a = np.array([[0,1,2],
             [1,2,3]])
b = np.array([[2,1,0],[2,1,0]])
print(a*b)

[[0 1 0]
 [2 2 0]]


In [ ]:
# 転置
print(a.T)

[[0 1]
 [1 2]
 [2 3]]
